Repository GDSC-BSIOTR/Student_Info, pull requests merged in 2022-10, with the labels that each got.

#73 Update student.json
  student.json
Labels: hacktober-accepted

#74 Update student.json
  student.json
Labels: hacktoberfest-accepted

#75 Update student.json
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#76 added my info
  student.json
Labels: hacktoberfest, hacktoberfest-accepted

#81 Update student.json
  student.json
Labels: hacktoberfest-accepted

#80 Added
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#79 Update student.json
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#82 Update student.json
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#83 Update student.json
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#85 Hacktoberfest-2022
  StudentInfo.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#86 add data of a student on line number 566
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#87 Update student.json
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#88 Update StudentInfo.json
  StudentInfo.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#89 Update student.json
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted

#90 changes done
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#91 Update student.json
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#93 Added Student Info
  StudentInfo.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#94 Update StudentInfo.json
  StudentInfo.json
Labels: hacktober-accepted, hacktoberfest-accepted

#95 Update student.json
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#96 added
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted

#97 Update student.json
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#99 added: studentInfo
  StudentInfo.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#102 Update student.json
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted

#103 Update student.json
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted

#104 Update student.json
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted

#105 Update student.json
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted

#106 Update student.json
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted

#107 Update student.json
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted

#108 Updated student.json
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted

#109 Update student.json
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted

#110 Update student.json
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted

#111 added student info
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#114 Update student.json
  student.json
Labels: hacktoberfest-accepted

#113 Update student.json
  student.json
Labels: hacktoberfest-accepted
