Repository GDSC-BSIOTR/Student_Info, pull requests merged in 2022-09, with the labels that each got.

#13 Added line 80
  student.json
Labels: hacktoberfest

#12 commit
  student.json
Labels: hacktoberfest

#41 Update student.json
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#59 ADDED MY INFO
  student.json
Labels: hacktoberfest-accepted

#60 added about me
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#64 self info
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#62 Update student.json
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#63 Added new name
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#65 committed!
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#66 added
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#67 added
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#68 Update student.json
  student.json
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#69 My name added
  student.json
Labels: hacktober-accepted

#70 Update student.json
  student.json
Labels: hacktober-accepted

#71 Added my info
  student.json
Labels: hacktober-accepted, hacktoberfest-accepted
